//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiitCustomerService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer", ConfigurationName="FiitCustomerService.CustomerPortType")]
    public interface CustomerPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/customer/#confirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitCustomerService.confirmResponse> confirmAsync(FiitCustomerService.confirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/customer/#getCustomerById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitCustomerService.getCustomerByIdResponse> getCustomerByIdAsync(FiitCustomerService.getCustomerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/customer/#getCustomerByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitCustomerService.getCustomerByEmailResponse> getCustomerByEmailAsync(FiitCustomerService.getCustomerByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/customer/#register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitCustomerService.registerResponse> registerAsync(FiitCustomerService.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/customer/#getEmailById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitCustomerService.getEmailByIdResponse> getEmailByIdAsync(FiitCustomerService.getEmailByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/customer/#checkPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitCustomerService.checkPasswordResponse> checkPasswordAsync(FiitCustomerService.checkPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirm", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class confirmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public confirmRequest()
        {
        }
        
        public confirmRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class confirmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool uspesnost;
        
        public confirmResponse()
        {
        }
        
        public confirmResponse(bool uspesnost)
        {
            this.uspesnost = uspesnost;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types")]
    public partial class Customer
    {
        
        private int idField;
        
        private string nameField;
        
        private string surnameField;
        
        private string emailField;
        
        private string genderField;
        
        private string currencyField;
        
        private string born_atField;
        
        private double coord_latField;
        
        private double coord_lonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string born_at
        {
            get
            {
                return this.born_atField;
            }
            set
            {
                this.born_atField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double coord_lat
        {
            get
            {
                return this.coord_latField;
            }
            set
            {
                this.coord_latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double coord_lon
        {
            get
            {
                return this.coord_lonField;
            }
            set
            {
                this.coord_lonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerById", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class getCustomerByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getCustomerByIdRequest()
        {
        }
        
        public getCustomerByIdRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerByIdResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class getCustomerByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FiitCustomerService.Customer customer;
        
        public getCustomerByIdResponse()
        {
        }
        
        public getCustomerByIdResponse(FiitCustomerService.Customer customer)
        {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerByEmail", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class getCustomerByEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public getCustomerByEmailRequest()
        {
        }
        
        public getCustomerByEmailRequest(string email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerByEmailResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class getCustomerByEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FiitCustomerService.Customer customer;
        
        public getCustomerByEmailResponse()
        {
        }
        
        public getCustomerByEmailResponse(FiitCustomerService.Customer customer)
        {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class registerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string surname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double coord_lat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double coord_lon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string born_at;
        
        public registerRequest()
        {
        }
        
        public registerRequest(string team_id, string name, string surname, string email, string gender, string currency, double coord_lat, double coord_lon, string born_at)
        {
            this.team_id = team_id;
            this.name = name;
            this.surname = surname;
            this.email = email;
            this.gender = gender;
            this.currency = currency;
            this.coord_lat = coord_lat;
            this.coord_lon = coord_lon;
            this.born_at = born_at;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class registerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public registerResponse()
        {
        }
        
        public registerResponse(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmailById", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class getEmailByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getEmailByIdRequest()
        {
        }
        
        public getEmailByIdRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmailByIdResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class getEmailByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public getEmailByIdResponse()
        {
        }
        
        public getEmailByIdResponse(string email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkPassword", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class checkPasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public checkPasswordRequest()
        {
        }
        
        public checkPasswordRequest(string id, string password)
        {
            this.id = id;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkPasswordResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", IsWrapped=true)]
    public partial class checkPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/customer/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool exists;
        
        public checkPasswordResponse()
        {
        }
        
        public checkPasswordResponse(bool exists)
        {
            this.exists = exists;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface CustomerPortTypeChannel : FiitCustomerService.CustomerPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class CustomerPortTypeClient : System.ServiceModel.ClientBase<FiitCustomerService.CustomerPortType>, FiitCustomerService.CustomerPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerPortTypeClient() : 
                base(CustomerPortTypeClient.GetDefaultBinding(), CustomerPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomerPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), CustomerPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitCustomerService.confirmResponse> FiitCustomerService.CustomerPortType.confirmAsync(FiitCustomerService.confirmRequest request)
        {
            return base.Channel.confirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitCustomerService.confirmResponse> confirmAsync(int id)
        {
            FiitCustomerService.confirmRequest inValue = new FiitCustomerService.confirmRequest();
            inValue.id = id;
            return ((FiitCustomerService.CustomerPortType)(this)).confirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitCustomerService.getCustomerByIdResponse> FiitCustomerService.CustomerPortType.getCustomerByIdAsync(FiitCustomerService.getCustomerByIdRequest request)
        {
            return base.Channel.getCustomerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitCustomerService.getCustomerByIdResponse> getCustomerByIdAsync(int id)
        {
            FiitCustomerService.getCustomerByIdRequest inValue = new FiitCustomerService.getCustomerByIdRequest();
            inValue.id = id;
            return ((FiitCustomerService.CustomerPortType)(this)).getCustomerByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitCustomerService.getCustomerByEmailResponse> FiitCustomerService.CustomerPortType.getCustomerByEmailAsync(FiitCustomerService.getCustomerByEmailRequest request)
        {
            return base.Channel.getCustomerByEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitCustomerService.getCustomerByEmailResponse> getCustomerByEmailAsync(string email)
        {
            FiitCustomerService.getCustomerByEmailRequest inValue = new FiitCustomerService.getCustomerByEmailRequest();
            inValue.email = email;
            return ((FiitCustomerService.CustomerPortType)(this)).getCustomerByEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitCustomerService.registerResponse> FiitCustomerService.CustomerPortType.registerAsync(FiitCustomerService.registerRequest request)
        {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitCustomerService.registerResponse> registerAsync(string team_id, string name, string surname, string email, string gender, string currency, double coord_lat, double coord_lon, string born_at)
        {
            FiitCustomerService.registerRequest inValue = new FiitCustomerService.registerRequest();
            inValue.team_id = team_id;
            inValue.name = name;
            inValue.surname = surname;
            inValue.email = email;
            inValue.gender = gender;
            inValue.currency = currency;
            inValue.coord_lat = coord_lat;
            inValue.coord_lon = coord_lon;
            inValue.born_at = born_at;
            return ((FiitCustomerService.CustomerPortType)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitCustomerService.getEmailByIdResponse> FiitCustomerService.CustomerPortType.getEmailByIdAsync(FiitCustomerService.getEmailByIdRequest request)
        {
            return base.Channel.getEmailByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitCustomerService.getEmailByIdResponse> getEmailByIdAsync(int id)
        {
            FiitCustomerService.getEmailByIdRequest inValue = new FiitCustomerService.getEmailByIdRequest();
            inValue.id = id;
            return ((FiitCustomerService.CustomerPortType)(this)).getEmailByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitCustomerService.checkPasswordResponse> FiitCustomerService.CustomerPortType.checkPasswordAsync(FiitCustomerService.checkPasswordRequest request)
        {
            return base.Channel.checkPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitCustomerService.checkPasswordResponse> checkPasswordAsync(string id, string password)
        {
            FiitCustomerService.checkPasswordRequest inValue = new FiitCustomerService.checkPasswordRequest();
            inValue.id = id;
            inValue.password = password;
            return ((FiitCustomerService.CustomerPortType)(this)).checkPasswordAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerPort))
            {
                return new System.ServiceModel.EndpointAddress("http://pis.predmety.fiit.stuba.sk/pis/ws/Customer");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomerPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.CustomerPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomerPortTypeClient.GetEndpointAddress(EndpointConfiguration.CustomerPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomerPort,
        }
    }
}
