//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiitTaskList
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist", ConfigurationName="FiitTaskList.TaskListPortType")]
    public interface TaskListPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#getAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.getAllResponse> getAllAsync(FiitTaskList.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#getById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.getByIdResponse> getByIdAsync(FiitTaskList.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#getByTeamId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.getByTeamIdResponse> getByTeamIdAsync(FiitTaskList.getByTeamIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#createTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.createTaskResponse> createTaskAsync(FiitTaskList.createTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#setCompleteness", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.setCompletenessResponse> setCompletenessAsync(FiitTaskList.setCompletenessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#setPublicity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.setPublicityResponse> setPublicityAsync(FiitTaskList.setPublicityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.updateResponse> updateAsync(FiitTaskList.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pis.predmety.fiit.stuba.sk/pis/tasklist/#delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FiitTaskList.deleteResponse> deleteAsync(FiitTaskList.deleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types")]
    public partial class Tasks
    {
        
        private int idField;
        
        private string creator_nameField;
        
        private bool is_publicField;
        
        private int completenessField;
        
        private string subjectField;
        
        private string descriptionField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string creator_name
        {
            get
            {
                return this.creator_nameField;
            }
            set
            {
                this.creator_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool is_public
        {
            get
            {
                return this.is_publicField;
            }
            set
            {
                this.is_publicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int completeness
        {
            get
            {
                return this.completenessField;
            }
            set
            {
                this.completenessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types")]
    public partial class Task
    {
        
        private int idField;
        
        private string creator_nameField;
        
        private bool is_publicField;
        
        private int completenessField;
        
        private string subjectField;
        
        private string descriptionField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string creator_name
        {
            get
            {
                return this.creator_nameField;
            }
            set
            {
                this.creator_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool is_public
        {
            get
            {
                return this.is_publicField;
            }
            set
            {
                this.is_publicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int completeness
        {
            get
            {
                return this.completenessField;
            }
            set
            {
                this.completenessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class getAllRequest
    {
        
        public getAllRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class getAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("task", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FiitTaskList.Tasks[] tasks;
        
        public getAllResponse()
        {
        }
        
        public getAllResponse(FiitTaskList.Tasks[] tasks)
        {
            this.tasks = tasks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class getByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getByIdRequest()
        {
        }
        
        public getByIdRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class getByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FiitTaskList.Task task;
        
        public getByIdResponse()
        {
        }
        
        public getByIdResponse(FiitTaskList.Task task)
        {
            this.task = task;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByTeamId", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class getByTeamIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        public getByTeamIdRequest()
        {
        }
        
        public getByTeamIdRequest(string team_id, string team_password)
        {
            this.team_id = team_id;
            this.team_password = team_password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByTeamIdResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class getByTeamIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("task", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FiitTaskList.Tasks[] tasks;
        
        public getByTeamIdResponse()
        {
        }
        
        public getByTeamIdResponse(FiitTaskList.Tasks[] tasks)
        {
            this.tasks = tasks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTask", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class createTaskRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creator_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_public;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp;
        
        public createTaskRequest()
        {
        }
        
        public createTaskRequest(string team_id, string team_password, string creator_name, bool is_public, string subject, string description, System.DateTime timestamp)
        {
            this.team_id = team_id;
            this.team_password = team_password;
            this.creator_name = creator_name;
            this.is_public = is_public;
            this.subject = subject;
            this.description = description;
            this.timestamp = timestamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTaskResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class createTaskResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int task_id;
        
        public createTaskResponse()
        {
        }
        
        public createTaskResponse(int task_id)
        {
            this.task_id = task_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCompleteness", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class setCompletenessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int completeness;
        
        public setCompletenessRequest()
        {
        }
        
        public setCompletenessRequest(int id, string team_id, string team_password, int completeness)
        {
            this.id = id;
            this.team_id = team_id;
            this.team_password = team_password;
            this.completeness = completeness;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCompletenessResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class setCompletenessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public setCompletenessResponse()
        {
        }
        
        public setCompletenessResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPublicity", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class setPublicityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_public;
        
        public setPublicityRequest()
        {
        }
        
        public setPublicityRequest(int id, string team_id, string team_password, bool is_public)
        {
            this.id = id;
            this.team_id = team_id;
            this.team_password = team_password;
            this.is_public = is_public;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPublicityResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class setPublicityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public setPublicityResponse()
        {
        }
        
        public setPublicityResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class updateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp;
        
        public updateRequest()
        {
        }
        
        public updateRequest(int id, string team_id, string team_password, string subject, string description, System.DateTime timestamp)
        {
            this.id = id;
            this.team_id = team_id;
            this.team_password = team_password;
            this.subject = subject;
            this.description = description;
            this.timestamp = timestamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class updateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public updateResponse()
        {
        }
        
        public updateResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class deleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string team_password;
        
        public deleteRequest()
        {
        }
        
        public deleteRequest(int id, string team_id, string team_password)
        {
            this.id = id;
            this.team_id = team_id;
            this.team_password = team_password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", IsWrapped=true)]
    public partial class deleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pis.predmety.fiit.stuba.sk/pis/tasklist/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public deleteResponse()
        {
        }
        
        public deleteResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface TaskListPortTypeChannel : FiitTaskList.TaskListPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class TaskListPortTypeClient : System.ServiceModel.ClientBase<FiitTaskList.TaskListPortType>, FiitTaskList.TaskListPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaskListPortTypeClient() : 
                base(TaskListPortTypeClient.GetDefaultBinding(), TaskListPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TaskListPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(TaskListPortTypeClient.GetBindingForEndpoint(endpointConfiguration), TaskListPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaskListPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaskListPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.getAllResponse> FiitTaskList.TaskListPortType.getAllAsync(FiitTaskList.getAllRequest request)
        {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.getAllResponse> getAllAsync()
        {
            FiitTaskList.getAllRequest inValue = new FiitTaskList.getAllRequest();
            return ((FiitTaskList.TaskListPortType)(this)).getAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.getByIdResponse> FiitTaskList.TaskListPortType.getByIdAsync(FiitTaskList.getByIdRequest request)
        {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.getByIdResponse> getByIdAsync(int id)
        {
            FiitTaskList.getByIdRequest inValue = new FiitTaskList.getByIdRequest();
            inValue.id = id;
            return ((FiitTaskList.TaskListPortType)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.getByTeamIdResponse> FiitTaskList.TaskListPortType.getByTeamIdAsync(FiitTaskList.getByTeamIdRequest request)
        {
            return base.Channel.getByTeamIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.getByTeamIdResponse> getByTeamIdAsync(string team_id, string team_password)
        {
            FiitTaskList.getByTeamIdRequest inValue = new FiitTaskList.getByTeamIdRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            return ((FiitTaskList.TaskListPortType)(this)).getByTeamIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.createTaskResponse> FiitTaskList.TaskListPortType.createTaskAsync(FiitTaskList.createTaskRequest request)
        {
            return base.Channel.createTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.createTaskResponse> createTaskAsync(string team_id, string team_password, string creator_name, bool is_public, string subject, string description, System.DateTime timestamp)
        {
            FiitTaskList.createTaskRequest inValue = new FiitTaskList.createTaskRequest();
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.creator_name = creator_name;
            inValue.is_public = is_public;
            inValue.subject = subject;
            inValue.description = description;
            inValue.timestamp = timestamp;
            return ((FiitTaskList.TaskListPortType)(this)).createTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.setCompletenessResponse> FiitTaskList.TaskListPortType.setCompletenessAsync(FiitTaskList.setCompletenessRequest request)
        {
            return base.Channel.setCompletenessAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.setCompletenessResponse> setCompletenessAsync(int id, string team_id, string team_password, int completeness)
        {
            FiitTaskList.setCompletenessRequest inValue = new FiitTaskList.setCompletenessRequest();
            inValue.id = id;
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.completeness = completeness;
            return ((FiitTaskList.TaskListPortType)(this)).setCompletenessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.setPublicityResponse> FiitTaskList.TaskListPortType.setPublicityAsync(FiitTaskList.setPublicityRequest request)
        {
            return base.Channel.setPublicityAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.setPublicityResponse> setPublicityAsync(int id, string team_id, string team_password, bool is_public)
        {
            FiitTaskList.setPublicityRequest inValue = new FiitTaskList.setPublicityRequest();
            inValue.id = id;
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.is_public = is_public;
            return ((FiitTaskList.TaskListPortType)(this)).setPublicityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.updateResponse> FiitTaskList.TaskListPortType.updateAsync(FiitTaskList.updateRequest request)
        {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.updateResponse> updateAsync(int id, string team_id, string team_password, string subject, string description, System.DateTime timestamp)
        {
            FiitTaskList.updateRequest inValue = new FiitTaskList.updateRequest();
            inValue.id = id;
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            inValue.subject = subject;
            inValue.description = description;
            inValue.timestamp = timestamp;
            return ((FiitTaskList.TaskListPortType)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiitTaskList.deleteResponse> FiitTaskList.TaskListPortType.deleteAsync(FiitTaskList.deleteRequest request)
        {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiitTaskList.deleteResponse> deleteAsync(int id, string team_id, string team_password)
        {
            FiitTaskList.deleteRequest inValue = new FiitTaskList.deleteRequest();
            inValue.id = id;
            inValue.team_id = team_id;
            inValue.team_password = team_password;
            return ((FiitTaskList.TaskListPortType)(this)).deleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskListPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskListPort))
            {
                return new System.ServiceModel.EndpointAddress("http://pis.predmety.fiit.stuba.sk/pis/ws/TaskList");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TaskListPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.TaskListPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TaskListPortTypeClient.GetEndpointAddress(EndpointConfiguration.TaskListPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TaskListPort,
        }
    }
}
